# Generated by Django 6.0.2 on 2026-02-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='チーム名')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=100, verbose_name='日本語名')),
                ('current_shoe_model', models.CharField(blank=True, max_length=100, verbose_name='着用バッシュ名')),
                ('fashion_style', models.CharField(blank=True, max_length=100, verbose_name='私服の系統')),
                ('param_fashion', models.IntegerField(default=3, verbose_name='オシャレ度')),
                ('param_sns', models.IntegerField(default=3, verbose_name='SNS更新頻度')),
                ('trivia', models.TextField(blank=True, verbose_name='豆知識・裏話')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.team', verbose_name='所属チーム')),
            ],
        ),
    ]
