# Generated by Django 6.0.2 on 2026-02-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ギャラリー画像')),
                ('caption', models.CharField(blank=True, help_text='例：2024開幕戦のセットアップ', max_length=200, verbose_name='キャプション')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='players.player')),
            ],
        ),
    ]
