# Generated by Django 6.0.2 on 2026-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_tunnelfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='instagram_id',
            field=models.CharField(blank=True, help_text='例: rui_8mura', max_length=50, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='twitter_id',
            field=models.CharField(blank=True, help_text='例: rui_8mura', max_length=50, verbose_name='X (Twitter) ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='チャンネルのURL', verbose_name='YouTube URL'),
        ),
    ]
