# Generated by Django 6.0.2 on 2026-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_instagram_id_player_twitter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color_primary',
            field=models.CharField(default='#333333', help_text='HEXコード (例: #552583)', max_length=7, verbose_name='メインカラー'),
        ),
        migrations.AddField(
            model_name='team',
            name='color_secondary',
            field=models.CharField(default='#eeeeee', help_text='HEXコード (例: #FDB927)', max_length=7, verbose_name='サブカラー'),
        ),
    ]
