# Generated by Django 6.0.2 on 2026-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_team_color_primary_team_color_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='apg',
            field=models.FloatField(default=0.0, verbose_name='平均アシスト'),
        ),
        migrations.AddField(
            model_name='player',
            name='name_en',
            field=models.CharField(blank=True, help_text='API連携用 (例: Rui Hachimura)', max_length=100, verbose_name='英語名'),
        ),
        migrations.AddField(
            model_name='player',
            name='ppg',
            field=models.FloatField(default=0.0, verbose_name='平均得点'),
        ),
        migrations.AddField(
            model_name='player',
            name='rpg',
            field=models.FloatField(default=0.0, verbose_name='平均リバウンド'),
        ),
    ]
