# Generated by Django 6.0.2 on 2026-02-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_apg_player_name_en_player_ppg_player_rpg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color_primary',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AlterField(
            model_name='team',
            name='color_secondary',
            field=models.CharField(default='#888888', max_length=7),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
