# Generated by Django 6.0.2 on 2026-02-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_team_color_primary_alter_team_color_secondary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_shoe_model',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fashion_style',
        ),
        migrations.RemoveField(
            model_name='player',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='param_fashion',
        ),
        migrations.RemoveField(
            model_name='player',
            name='param_sns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trivia',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twitter_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='player',
            name='fashion_brands',
            field=models.TextField(blank=True, null=True, verbose_name='よく着ているブランド'),
        ),
        migrations.AddField(
            model_name='player',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='player',
            name='podcast',
            field=models.URLField(blank=True, null=True, verbose_name='ポッドキャスト URL'),
        ),
        migrations.AddField(
            model_name='player',
            name='shoe_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='着用バッシュ'),
        ),
        migrations.AddField(
            model_name='player',
            name='ura_nba',
            field=models.TextField(blank=True, null=True, verbose_name='ウラNBA（豆知識）'),
        ),
        migrations.AddField(
            model_name='player',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/', verbose_name='選手画像'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='英語名'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='players.team', verbose_name='所属チーム'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TunnelFit',
        ),
    ]
