# Generated by Django 6.0.2 on 2026-02-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_player_current_shoe_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ギャラリー画像')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='キャプション')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='players.player')),
            ],
        ),
    ]
